CREATE TABLE IF NOT EXISTS billing.sku_billing_trigger_matrix (
  sku_code text PRIMARY KEY,
  payment_trigger text NOT NULL,
  delivery_trigger text NOT NULL,
  acceptance_trigger text NOT NULL,
  billing_trigger text NOT NULL,
  settlement_cycle text NOT NULL,
  refund_entry text NOT NULL,
  compensation_entry text NOT NULL,
  dispute_freeze_trigger text NOT NULL,
  resume_settlement_trigger text NOT NULL,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  updated_at timestamptz NOT NULL DEFAULT now()
);

INSERT INTO billing.sku_billing_trigger_matrix (
  sku_code,
  payment_trigger,
  delivery_trigger,
  acceptance_trigger,
  billing_trigger,
  settlement_cycle,
  refund_entry,
  compensation_entry,
  dispute_freeze_trigger,
  resume_settlement_trigger,
  metadata
) VALUES
  (
    'FILE_STD',
    'order_contract_effective_lock_once',
    'seller_publish_single_package',
    'buyer_manual_accept_or_timeout',
    'bill_once_after_acceptance',
    't_plus_1_once',
    'pre_acceptance_cancel_or_acceptance_failed',
    'delivery_defect_or_delay',
    'freeze_on_dispute_opened',
    'resume_on_dispute_closed_with_ruling',
    '{"seed":"db034","sku":"FILE_STD","source":"docs/03-db/sku-billing-trigger-matrix.md"}'::jsonb
  ),
  (
    'FILE_SUB',
    'lock_before_each_subscription_cycle',
    'generate_delivery_batch_each_cycle',
    'cycle_window_manual_acceptance',
    'bill_per_cycle_after_acceptance',
    'monthly_cycle',
    'refund_current_cycle_if_not_delivered',
    'compensate_on_repeated_missing_delivery',
    'freeze_future_cycles_on_dispute_opened',
    'resume_after_dispute_closed_for_cycle',
    '{"seed":"db034","sku":"FILE_SUB","source":"docs/03-db/sku-billing-trigger-matrix.md"}'::jsonb
  ),
  (
    'SHARE_RO',
    'lock_before_share_grant_activation',
    'readonly_share_grant_enabled',
    'accessibility_check_passed',
    'bill_once_on_grant_effective',
    't_plus_1_once',
    'refund_if_grant_not_effective',
    'compensate_on_scope_or_access_violation',
    'freeze_on_share_dispute_opened',
    'resume_on_dispute_closed_after_fix',
    '{"seed":"db034","sku":"SHARE_RO","source":"docs/03-db/sku-billing-trigger-matrix.md"}'::jsonb
  ),
  (
    'API_SUB',
    'lock_before_subscription_cycle_start',
    'api_key_and_quota_provisioned',
    'first_success_call_or_cycle_acceptance',
    'bill_cycle_after_enable_and_acceptance',
    'monthly_cycle',
    'refund_current_cycle_if_unavailable',
    'compensate_on_sla_breach',
    'freeze_current_cycle_on_sla_dispute',
    'resume_on_sla_dispute_closed',
    '{"seed":"db034","sku":"API_SUB","source":"docs/03-db/sku-billing-trigger-matrix.md"}'::jsonb
  ),
  (
    'API_PPU',
    'lock_prepaid_quota_or_minimum_commit',
    'api_key_enabled_for_metering',
    'usage_reconciliation_window_confirmed',
    'bill_by_metered_usage',
    'daily_with_monthly_statement',
    'refund_failed_batch_or_unused_quota',
    'compensate_on_metering_or_throttling_fault',
    'freeze_metered_settlement_on_dispute',
    'resume_after_metering_reconcile',
    '{"seed":"db034","sku":"API_PPU","source":"docs/03-db/sku-billing-trigger-matrix.md"}'::jsonb
  ),
  (
    'QRY_LITE',
    'lock_before_query_job_execution',
    'query_job_succeeded_result_available',
    'result_integrity_and_download_check',
    'bill_once_after_task_acceptance',
    't_plus_1_once',
    'refund_if_task_failed_or_unavailable',
    'compensate_on_execution_unavailability',
    'freeze_on_query_result_dispute',
    'resume_after_result_recheck_closed',
    '{"seed":"db034","sku":"QRY_LITE","source":"docs/03-db/sku-billing-trigger-matrix.md"}'::jsonb
  ),
  (
    'SBX_STD',
    'lock_before_workspace_provision',
    'workspace_account_quota_ready',
    'login_and_probe_check_passed',
    'bill_after_workspace_activation_acceptance',
    'monthly_resource_cycle',
    'refund_if_workspace_not_ready',
    'compensate_on_resource_or_isolation_fault',
    'freeze_on_security_or_isolation_dispute',
    'resume_after_risk_cleared_dispute_closed',
    '{"seed":"db034","sku":"SBX_STD","source":"docs/03-db/sku-billing-trigger-matrix.md"}'::jsonb
  ),
  (
    'RPT_STD',
    'lock_after_report_order_created',
    'report_generated_and_downloadable',
    'buyer_accept_or_timeout_acceptance',
    'bill_once_after_report_acceptance',
    't_plus_1_once',
    'refund_if_report_not_generated_or_rejected',
    'compensate_on_critical_report_defect',
    'freeze_on_report_quality_dispute',
    'resume_on_review_passed_dispute_closed',
    '{"seed":"db034","sku":"RPT_STD","source":"docs/03-db/sku-billing-trigger-matrix.md"}'::jsonb
  )
ON CONFLICT (sku_code) DO UPDATE
SET
  payment_trigger = EXCLUDED.payment_trigger,
  delivery_trigger = EXCLUDED.delivery_trigger,
  acceptance_trigger = EXCLUDED.acceptance_trigger,
  billing_trigger = EXCLUDED.billing_trigger,
  settlement_cycle = EXCLUDED.settlement_cycle,
  refund_entry = EXCLUDED.refund_entry,
  compensation_entry = EXCLUDED.compensation_entry,
  dispute_freeze_trigger = EXCLUDED.dispute_freeze_trigger,
  resume_settlement_trigger = EXCLUDED.resume_settlement_trigger,
  metadata = EXCLUDED.metadata,
  updated_at = NOW();
