import { NotificationItem } from '@/types/notifications'

function nowIsoMinus(mins: number) {
  return new Date(Date.now() - mins * 60 * 1000).toISOString()
}

export const BUYER_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'bn1',
    title: '订阅即将到期',
    desc: '企业工商风险数据将在 29 天后到期。',
    detail: '建议在到期前 14 天提交续订申请，避免模型调用中断。当前剩余额度 35%，供应商支持自动续约。',
    level: 'warning',
    status: 'unread',
    time: '今天 10:40',
    timestamp: nowIsoMinus(35),
    category: 'subscription',
    source: 'platform_internal',
    priority: 4,
    pinned: true,
    requestId: 'req_20260429_001',
    relatedEntityType: 'subscription',
    relatedEntityId: 'subscription_20260328_001',
    targetPath: '/console/buyer/subscriptions?focus=subscription_20260328_001',
    replies: [],
  },
  {
    id: 'bn2',
    title: '申请待补充材料',
    desc: '医疗健康知识图谱申请缺少资质证明。',
    detail: '平台合规引擎识别缺少《数据使用资质说明》附件。请在 24 小时内补充，逾期将自动退回。',
    level: 'warning',
    status: 'unread',
    time: '今天 09:10',
    timestamp: nowIsoMinus(120),
    category: 'request',
    source: 'service_external',
    priority: 5,
    pinned: false,
    requestId: 'req_20260429_002',
    relatedEntityType: 'request',
    relatedEntityId: 'request_20260427_002',
    targetPath: '/console/buyer/requests?focus=request_20260427_002',
    replies: [{ id: 'r1', author: '平台审核员-周宁', role: 'admin', content: '可先上传机构证明模板，我们会优先复核。', createdAt: '今天 09:21' }],
  },
  {
    id: 'bn3',
    title: '发票已开具',
    desc: '订单 order_20260428_001 发票已可下载。',
    detail: '发票抬头与税号已校验通过，建议在账期内完成归档。',
    level: 'success',
    status: 'read',
    time: '昨天 18:25',
    timestamp: nowIsoMinus(980),
    category: 'billing',
    source: 'system_internal',
    priority: 2,
    pinned: false,
    relatedEntityType: 'order',
    relatedEntityId: 'order_20260428_001',
    targetPath: '/console/buyer/orders?focus=order_20260428_001',
    replies: [],
  },
  {
    id: 'bn4',
    title: '调用成功率提升',
    desc: '过去 24h API 成功率达到 99.2%。',
    detail: '上游供应商已完成节点扩容，95 分位响应时间下降 18%。建议观察 72h 稳态后切换高并发策略。',
    level: 'info',
    status: 'read',
    time: '昨天 11:20',
    timestamp: nowIsoMinus(1390),
    category: 'system',
    source: 'system_internal',
    priority: 2,
    pinned: false,
    requestId: 'req_20260428_992',
    targetPath: '/console/buyer/usage',
    replies: [],
  },
]

export const SELLER_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'sn1',
    title: '调用配额预警',
    desc: '企业工商风险数据调用已达 82%。',
    detail: '高优先级买家的订阅即将触发限流阈值，建议调整套餐配额或通知买家升级。',
    level: 'warning',
    status: 'unread',
    time: '今天 10:40',
    timestamp: nowIsoMinus(45),
    category: 'system',
    source: 'system_internal',
    priority: 4,
    pinned: true,
    relatedEntityType: 'subscription',
    relatedEntityId: 'sub_seller_001',
    targetPath: '/console/seller/customers',
    replies: [],
  },
  {
    id: 'sn2',
    title: '链上提交失败',
    desc: '订单 order_12345 提交失败需重试。',
    detail: 'Chain gateway 返回 nonce 冲突，系统已自动重试 2 次未成功。请在链监控页手动重试。',
    level: 'error',
    status: 'unread',
    time: '今天 09:20',
    timestamp: nowIsoMinus(125),
    category: 'chain',
    source: 'service_external',
    priority: 5,
    pinned: false,
    txHash: '0x7f2a...e91d',
    relatedEntityType: 'order',
    relatedEntityId: 'order_12345',
    targetPath: '/console/seller/requests',
    replies: [{ id: 'sr1', author: '链路机器人', role: 'system', content: '建议等待 2 分钟后再次提交。', createdAt: '今天 09:22' }],
  },
  {
    id: 'sn3',
    title: '订阅激活成功',
    desc: '新客户订阅已生效。',
    detail: '订阅 license_scope=commercial，已自动下发 API 凭证并完成审计记录。',
    level: 'success',
    status: 'read',
    time: '昨天 16:12',
    timestamp: nowIsoMinus(1100),
    category: 'subscription',
    source: 'platform_internal',
    priority: 2,
    pinned: false,
    relatedEntityType: 'subscription',
    relatedEntityId: 'sub_20260428_321',
    targetPath: '/console/seller/customers',
    replies: [],
  },
]

export const ADMIN_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'an1',
    title: '一致性异常',
    desc: '申请 req_67890 投影状态不一致。',
    detail: '业务状态已 APPROVED，但 projection_status=OUT_OF_SYNC。建议执行事件重放并追踪通知链路。',
    level: 'warning',
    status: 'unread',
    time: '今天 10:40',
    timestamp: nowIsoMinus(30),
    category: 'risk',
    source: 'system_internal',
    priority: 5,
    pinned: true,
    requestId: 'req_67890',
    relatedEntityType: 'request',
    relatedEntityId: 'req_67890',
    targetPath: '/admin/console/consistency',
    replies: [],
  },
  {
    id: 'an2',
    title: '链上提交失败',
    desc: '订单 order_12345 已重试 3 次失败。',
    detail: '失败原因为 gas 估算异常。建议进入链监控执行手动刷新并复核合约参数。',
    level: 'error',
    status: 'unread',
    time: '今天 09:20',
    timestamp: nowIsoMinus(130),
    category: 'chain',
    source: 'service_external',
    priority: 5,
    pinned: false,
    txHash: '0xabd3...9912',
    relatedEntityType: 'order',
    relatedEntityId: 'order_12345',
    targetPath: '/admin/console/consistency',
    replies: [],
  },
  {
    id: 'an3',
    title: '通知重放成功',
    desc: 'notif_11111 replay 完成。',
    detail: '重放后买家与卖家均已收到审批通过通知，状态回执正常。',
    level: 'success',
    status: 'read',
    time: '昨天 16:12',
    timestamp: nowIsoMinus(1130),
    category: 'system',
    source: 'platform_internal',
    priority: 2,
    pinned: false,
    relatedEntityType: 'ticket',
    relatedEntityId: 'notif_11111',
    targetPath: '/admin/console/consistency',
    replies: [],
  },
]
