use serde::{Deserialize, Serialize};
use serde_json::Value;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CommitOrderDeliveryRequest {
    pub branch: String,
    pub object_uri: Option<String>,
    pub content_type: Option<String>,
    pub size_bytes: Option<i64>,
    pub content_hash: Option<String>,
    pub encryption_algo: Option<String>,
    pub plaintext_visible_to_platform: Option<bool>,
    pub storage_namespace_id: Option<String>,
    pub key_cipher: Option<String>,
    pub key_control_mode: Option<String>,
    pub unwrap_policy_json: Option<Value>,
    pub key_version: Option<String>,
    pub expire_at: Option<String>,
    pub download_limit: Option<i32>,
    pub delivery_commit_hash: Option<String>,
    pub receipt_hash: Option<String>,
    pub report_type: Option<String>,
    pub asset_object_id: Option<String>,
    pub app_id: Option<String>,
    pub app_name: Option<String>,
    pub app_type: Option<String>,
    pub client_id: Option<String>,
    pub quota_json: Option<Value>,
    pub rate_limit_json: Option<Value>,
    pub upstream_mode: Option<String>,
    pub metadata: Option<Value>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CommitOrderDeliveryResponse {
    pub data: CommitOrderDeliveryResponseData,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CommitOrderDeliveryResponseData {
    pub order_id: String,
    pub delivery_id: String,
    pub branch: String,
    pub previous_state: String,
    pub current_state: String,
    pub payment_status: String,
    pub delivery_status: String,
    pub acceptance_status: String,
    pub settlement_status: String,
    pub dispute_status: String,
    pub object_id: Option<String>,
    pub envelope_id: Option<String>,
    pub ticket_id: Option<String>,
    pub bucket_name: Option<String>,
    pub object_key: Option<String>,
    pub expires_at: Option<String>,
    pub download_limit: Option<i32>,
    pub receipt_hash: Option<String>,
    pub delivery_commit_hash: Option<String>,
    pub committed_at: String,
    pub app_id: Option<String>,
    pub app_name: Option<String>,
    pub app_type: Option<String>,
    pub client_id: Option<String>,
    pub api_credential_id: Option<String>,
    pub api_key: Option<String>,
    pub api_key_hint: Option<String>,
    pub quota_json: Option<Value>,
    pub rate_limit_json: Option<Value>,
    pub upstream_mode: Option<String>,
    pub operation: Option<String>,
    pub endpoint_uri: Option<String>,
    pub credential_status: Option<String>,
    pub report_artifact_id: Option<String>,
    pub report_type: Option<String>,
    pub report_version_no: Option<i32>,
    pub report_status: Option<String>,
    pub report_hash: Option<String>,
}
