import {
  DataProduct,
  OpsRiskEvent,
  ProductField,
  ProductSampleRow,
  SupplierMetric,
} from "./types";

export const industryOptions = [
  { key: "finance", label: "金融" },
  { key: "transport", label: "交通" },
  { key: "healthcare", label: "医疗" },
  { key: "government", label: "政务" },
  { key: "enterprise", label: "企业经营" },
  { key: "ai_training", label: "AI训练数据" },
] as const;

export const marketplaceProducts: DataProduct[] = [
  {
    id: "fin-api-risk-v2",
    name: "企业交易风险评分 API",
    supplier: "TrustLedger Data Lab",
    industry: ["finance", "enterprise"],
    dataType: "api",
    delivery: "api",
    priceMode: "subscription",
    updateFrequency: "daily",
    coverage: "全国 340+ 城市",
    region: "cn_east",
    trial: true,
    tags: ["已认证", "可商用", "有样例", "审计链路完备"],
    description: "用于贷前反欺诈和商户风险预警，支持细粒度字段级权限。",
    priceCents: 249000,
    fieldCount: 126,
    sampleRows: 100,
    qualityScore: 96,
    pii: "approval_required",
  },
  {
    id: "logistics-flow-file",
    name: "全国干线物流流量月报",
    supplier: "TransitScope Analytics",
    industry: ["transport", "government"],
    dataType: "file",
    delivery: "file_download",
    priceMode: "one_off",
    updateFrequency: "monthly",
    coverage: "31 省级行政区",
    region: "cn_north",
    trial: false,
    tags: ["已认证", "可商用"],
    description: "物流热力指数、路线拥堵指数、节点吞吐与异常事件聚合。",
    priceCents: 98000,
    fieldCount: 78,
    sampleRows: 80,
    qualityScore: 91,
    pii: "none",
  },
  {
    id: "health-share-outcome",
    name: "门急诊就诊结局共享数据集",
    supplier: "MedGraph Consortium",
    industry: ["healthcare", "ai_training"],
    dataType: "share",
    delivery: "share_link",
    priceMode: "subscription",
    updateFrequency: "weekly",
    coverage: "全国 80+ 三甲医院",
    region: "global",
    trial: true,
    tags: ["含PII需审批", "脱敏", "有样例"],
    description: "结构化病历片段，支持研究项目白名单审批与审计留痕。",
    priceCents: 368000,
    fieldCount: 312,
    sampleRows: 120,
    qualityScore: 88,
    pii: "masked",
  },
  {
    id: "gov-enterprise-report",
    name: "企业经营景气度指数报告",
    supplier: "CityScope Insights",
    industry: ["government", "enterprise", "finance"],
    dataType: "report",
    delivery: "file_download",
    priceMode: "one_off",
    updateFrequency: "monthly",
    coverage: "重点 100 城",
    region: "cn_east",
    trial: true,
    tags: ["已认证", "有样例", "可商用"],
    description: "企业现金流、招工、税务等指标综合构建景气度评分。",
    priceCents: 56000,
    fieldCount: 44,
    sampleRows: 40,
    qualityScore: 94,
    pii: "none",
  },
];

export const productFields: ProductField[] = [
  {
    name: "merchant_id",
    type: "string",
    description: "商户主体唯一标识（经匿名化）",
    sample: "M_9f3da***",
    sensitive: true,
    quality: 98,
  },
  {
    name: "txn_amount",
    type: "decimal(18,2)",
    description: "交易金额（人民币）",
    sample: "2580.00",
    sensitive: false,
    quality: 97,
  },
  {
    name: "txn_city",
    type: "string",
    description: "交易发生城市",
    sample: "Shanghai",
    sensitive: false,
    quality: 95,
  },
  {
    name: "risk_level",
    type: "enum",
    description: "风险等级评分映射",
    sample: "HIGH",
    sensitive: false,
    quality: 92,
  },
];

export const sampleRows: ProductSampleRow[] = Array.from({ length: 100 }).map((_, idx) => ({
  index: idx + 1,
  merchant_id: `M_${1000 + idx}***`,
  txn_amount: `${(Math.random() * 8000 + 200).toFixed(2)}`,
  txn_city: ["Shanghai", "Shenzhen", "Chengdu", "Beijing"][idx % 4] ?? "Shanghai",
  event_time: `2026-04-${String((idx % 28) + 1).padStart(2, "0")} 10:${String(
    idx % 60,
  ).padStart(2, "0")}:00`,
}));

export const supplierMetrics: SupplierMetric[] = [
  {
    month: "Jan",
    revenue: 420000,
    subscriptions: 38,
    applications: 96,
    calls: 1240000,
    conversion: 0.39,
  },
  {
    month: "Feb",
    revenue: 510000,
    subscriptions: 46,
    applications: 112,
    calls: 1390000,
    conversion: 0.41,
  },
  {
    month: "Mar",
    revenue: 640000,
    subscriptions: 59,
    applications: 129,
    calls: 1710000,
    conversion: 0.45,
  },
];

export const opsRiskEvents: OpsRiskEvent[] = [
  {
    id: "risk-0007",
    riskLevel: "high",
    type: "abnormal_replay_attempt",
    subject: "tenant_developer@buyer-a",
    requestId: "req-172de8b9",
    txHash: "0x16ff...a91d",
    chainStatus: "confirmed",
    projectionStatus: "synced",
    at: "2026-04-25T09:30:02Z",
  },
  {
    id: "risk-0008",
    riskLevel: "medium",
    type: "pii_scope_expansion",
    subject: "seller_operator@supplier-c",
    requestId: "req-17aac111",
    txHash: "0x83bc...c810",
    chainStatus: "pending",
    projectionStatus: "lagging",
    at: "2026-04-25T09:34:12Z",
  },
];
