DROP FUNCTION IF EXISTS common.tg_write_outbox();
DROP FUNCTION IF EXISTS common.tg_dispute_status_history();
DROP FUNCTION IF EXISTS common.tg_order_status_history();
DROP FUNCTION IF EXISTS common.tg_set_updated_at();

DROP SCHEMA IF EXISTS ecosystem CASCADE;
DROP SCHEMA IF EXISTS crosschain CASCADE;
DROP SCHEMA IF EXISTS ml CASCADE;
DROP SCHEMA IF EXISTS ops CASCADE;
DROP SCHEMA IF EXISTS developer CASCADE;
DROP SCHEMA IF EXISTS search CASCADE;
DROP SCHEMA IF EXISTS chain CASCADE;
DROP SCHEMA IF EXISTS audit CASCADE;
DROP SCHEMA IF EXISTS risk CASCADE;
DROP SCHEMA IF EXISTS support CASCADE;
DROP SCHEMA IF EXISTS payment CASCADE;
DROP SCHEMA IF EXISTS billing CASCADE;
DROP SCHEMA IF EXISTS delivery CASCADE;
DROP SCHEMA IF EXISTS trade CASCADE;
DROP SCHEMA IF EXISTS review CASCADE;
DROP SCHEMA IF EXISTS contract CASCADE;
DROP SCHEMA IF EXISTS catalog CASCADE;
DROP SCHEMA IF EXISTS authz CASCADE;
DROP SCHEMA IF EXISTS core CASCADE;
DROP SCHEMA IF EXISTS common CASCADE;
-- Payment settlement sync: payment schema drops before billing/common teardown.
