DROP TRIGGER IF EXISTS trg_subject_role_binding_updated_at ON authz.subject_role_binding;
DROP TRIGGER IF EXISTS trg_fabric_identity_binding_updated_at ON iam.fabric_identity_binding;
DROP TRIGGER IF EXISTS trg_certificate_record_updated_at ON iam.certificate_record;
DROP TRIGGER IF EXISTS trg_fabric_ca_registry_updated_at ON iam.fabric_ca_registry;
DROP TRIGGER IF EXISTS trg_step_up_challenge_updated_at ON iam.step_up_challenge;
DROP TRIGGER IF EXISTS trg_external_identity_binding_updated_at ON iam.external_identity_binding;
DROP TRIGGER IF EXISTS trg_sso_connection_updated_at ON iam.sso_connection;
DROP TRIGGER IF EXISTS trg_user_session_updated_at ON iam.user_session;
DROP TRIGGER IF EXISTS trg_refresh_token_family_updated_at ON iam.refresh_token_family;
DROP TRIGGER IF EXISTS trg_trusted_device_updated_at ON iam.trusted_device;
DROP TRIGGER IF EXISTS trg_mfa_authenticator_updated_at ON iam.mfa_authenticator;
DROP TRIGGER IF EXISTS trg_auth_method_binding_updated_at ON iam.auth_method_binding;
DROP TRIGGER IF EXISTS trg_identity_proof_updated_at ON iam.identity_proof;
DROP TRIGGER IF EXISTS trg_invitation_updated_at ON iam.invitation;
DROP TRIGGER IF EXISTS trg_execution_environment_updated_at ON core.execution_environment;
DROP TRIGGER IF EXISTS trg_connector_updated_at ON core.connector;
DROP TRIGGER IF EXISTS trg_application_updated_at ON core.application;
DROP TRIGGER IF EXISTS trg_user_account_updated_at ON core.user_account;
DROP TRIGGER IF EXISTS trg_department_updated_at ON core.department;
DROP TRIGGER IF EXISTS trg_organization_updated_at ON core.organization;

DROP TABLE IF EXISTS authz.subject_role_binding CASCADE;
DROP TABLE IF EXISTS authz.role_permission CASCADE;
DROP TABLE IF EXISTS authz.permission_definition CASCADE;
DROP TABLE IF EXISTS authz.role_definition CASCADE;
DROP TABLE IF EXISTS iam.certificate_revocation_record CASCADE;
DROP TABLE IF EXISTS iam.fabric_identity_binding CASCADE;
DROP TABLE IF EXISTS iam.certificate_record CASCADE;
DROP TABLE IF EXISTS iam.fabric_ca_registry CASCADE;
DROP TABLE IF EXISTS iam.step_up_challenge CASCADE;
DROP TABLE IF EXISTS iam.external_identity_binding CASCADE;
DROP TABLE IF EXISTS iam.sso_connection CASCADE;
DROP TABLE IF EXISTS iam.user_session CASCADE;
DROP TABLE IF EXISTS iam.refresh_token_family CASCADE;
DROP TABLE IF EXISTS iam.trusted_device CASCADE;
DROP TABLE IF EXISTS iam.mfa_authenticator CASCADE;
DROP TABLE IF EXISTS iam.auth_method_binding CASCADE;
DROP TABLE IF EXISTS iam.identity_proof CASCADE;
DROP TABLE IF EXISTS iam.invitation CASCADE;
DROP TABLE IF EXISTS core.execution_environment CASCADE;
DROP TABLE IF EXISTS core.connector CASCADE;
DROP TABLE IF EXISTS core.service_identity CASCADE;
DROP TABLE IF EXISTS core.application CASCADE;
DROP TABLE IF EXISTS core.did_binding CASCADE;
DROP TABLE IF EXISTS core.user_account CASCADE;
DROP TABLE IF EXISTS core.department CASCADE;
DROP TABLE IF EXISTS core.organization CASCADE;
-- Trust-boundary baseline sync: downgrade order unchanged.

-- Payment settlement sync: no structural change required in this migration; payment domain changes are handled by dedicated payment/billing migrations.
