DROP TRIGGER IF EXISTS trg_dispute_status_history ON support.dispute_case;
DROP TRIGGER IF EXISTS trg_dispute_case_updated_at ON support.dispute_case;
DROP TRIGGER IF EXISTS trg_reconciliation_diff_updated_at ON payment.reconciliation_diff;
DROP TRIGGER IF EXISTS trg_reconciliation_statement_updated_at ON payment.reconciliation_statement;
DROP TRIGGER IF EXISTS trg_payout_instruction_updated_at ON payment.payout_instruction;
DROP TRIGGER IF EXISTS trg_refund_intent_updated_at ON payment.refund_intent;
DROP TRIGGER IF EXISTS trg_payment_intent_updated_at ON payment.payment_intent;
DROP TRIGGER IF EXISTS trg_payment_payout_preference_updated_at ON payment.payout_preference;
DROP TRIGGER IF EXISTS trg_payment_corridor_policy_updated_at ON payment.corridor_policy;
DROP TRIGGER IF EXISTS trg_payment_provider_account_updated_at ON payment.provider_account;
DROP TRIGGER IF EXISTS trg_payment_jurisdiction_profile_updated_at ON payment.jurisdiction_profile;
DROP TRIGGER IF EXISTS trg_payment_provider_updated_at ON payment.provider;
DROP TRIGGER IF EXISTS trg_compensation_record_updated_at ON billing.compensation_record;
DROP TRIGGER IF EXISTS trg_invoice_request_updated_at ON billing.invoice_request;
DROP TRIGGER IF EXISTS trg_refund_record_updated_at ON billing.refund_record;
DROP TRIGGER IF EXISTS trg_settlement_record_updated_at ON billing.settlement_record;
DROP TRIGGER IF EXISTS trg_deposit_record_updated_at ON billing.deposit_record;
DROP TRIGGER IF EXISTS trg_escrow_ledger_updated_at ON billing.escrow_ledger;
DROP TRIGGER IF EXISTS trg_wallet_account_updated_at ON billing.wallet_account;
DROP TRIGGER IF EXISTS trg_fee_rule_updated_at ON billing.fee_rule;

DROP TABLE IF EXISTS risk.blacklist_entry CASCADE;
DROP TABLE IF EXISTS risk.reputation_snapshot CASCADE;
DROP TABLE IF EXISTS risk.rating_record CASCADE;
DROP TABLE IF EXISTS support.decision_record CASCADE;
DROP TABLE IF EXISTS support.evidence_object CASCADE;
DROP TABLE IF EXISTS support.dispute_status_history CASCADE;
DROP TABLE IF EXISTS support.dispute_case CASCADE;
DROP TABLE IF EXISTS billing.compensation_record CASCADE;
DROP TABLE IF EXISTS billing.invoice_request CASCADE;
DROP TABLE IF EXISTS payment.reconciliation_diff CASCADE;
DROP TABLE IF EXISTS payment.reconciliation_statement CASCADE;
DROP TABLE IF EXISTS payment.payout_instruction CASCADE;
DROP TABLE IF EXISTS payment.refund_intent CASCADE;
DROP TABLE IF EXISTS payment.payment_webhook_event CASCADE;
DROP TABLE IF EXISTS payment.payment_transaction CASCADE;
DROP TABLE IF EXISTS payment.payment_intent CASCADE;
DROP TABLE IF EXISTS payment.payout_preference CASCADE;
DROP TABLE IF EXISTS payment.corridor_policy CASCADE;
DROP TABLE IF EXISTS payment.provider_account CASCADE;
DROP TABLE IF EXISTS payment.jurisdiction_profile CASCADE;
DROP TABLE IF EXISTS payment.provider CASCADE;
DROP TABLE IF EXISTS billing.refund_record CASCADE;
DROP TABLE IF EXISTS billing.penalty_event CASCADE;
DROP TABLE IF EXISTS billing.settlement_record CASCADE;
DROP TABLE IF EXISTS billing.billing_event CASCADE;
DROP TABLE IF EXISTS billing.deposit_record CASCADE;
DROP TABLE IF EXISTS billing.escrow_ledger CASCADE;
DROP TABLE IF EXISTS billing.account_ledger_entry CASCADE;
DROP TABLE IF EXISTS billing.wallet_account CASCADE;
DROP TABLE IF EXISTS billing.fee_preview CASCADE;
DROP TABLE IF EXISTS billing.fee_rule_version CASCADE;
DROP TABLE IF EXISTS billing.fee_rule CASCADE;
DROP TABLE IF EXISTS billing.token_asset CASCADE;
-- Payment settlement sync: fee/payment/reconciliation objects removed before billing schema teardown.
