//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "admin_event_entity")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub admin_event_time: Option<i64>,
    pub realm_id: Option<String>,
    pub operation_type: Option<String>,
    pub auth_realm_id: Option<String>,
    pub auth_client_id: Option<String>,
    pub auth_user_id: Option<String>,
    pub ip_address: Option<String>,
    pub resource_path: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub representation: Option<String>,
    pub error: Option<String>,
    pub resource_type: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub details_json: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
