//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "authentication_execution")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub alias: Option<String>,
    pub authenticator: Option<String>,
    pub realm_id: Option<String>,
    pub flow_id: Option<String>,
    pub requirement: Option<i32>,
    pub priority: Option<i32>,
    pub authenticator_flow: bool,
    pub auth_flow_id: Option<String>,
    pub auth_config: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::authentication_flow::Entity",
        from = "Column::FlowId",
        to = "super::authentication_flow::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    AuthenticationFlow,
    #[sea_orm(
        belongs_to = "super::realm::Entity",
        from = "Column::RealmId",
        to = "super::realm::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Realm,
}

impl Related<super::authentication_flow::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AuthenticationFlow.def()
    }
}

impl Related<super::realm::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Realm.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
