//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "broker_link")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub identity_provider: String,
    pub storage_provider_id: Option<String>,
    pub realm_id: String,
    pub broker_user_id: Option<String>,
    pub broker_username: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub token: Option<String>,
    #[sea_orm(primary_key, auto_increment = false)]
    pub user_id: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
