//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "client")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub enabled: bool,
    pub full_scope_allowed: bool,
    pub client_id: Option<String>,
    pub not_before: Option<i32>,
    pub public_client: bool,
    pub secret: Option<String>,
    pub base_url: Option<String>,
    pub bearer_only: bool,
    pub management_url: Option<String>,
    pub surrogate_auth_required: bool,
    pub realm_id: Option<String>,
    pub protocol: Option<String>,
    pub node_rereg_timeout: Option<i32>,
    pub frontchannel_logout: bool,
    pub consent_required: bool,
    pub name: Option<String>,
    pub service_accounts_enabled: bool,
    pub client_authenticator_type: Option<String>,
    pub root_url: Option<String>,
    pub description: Option<String>,
    pub registration_token: Option<String>,
    pub standard_flow_enabled: bool,
    pub implicit_flow_enabled: bool,
    pub direct_access_grants_enabled: bool,
    pub always_display_in_console: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::client_attributes::Entity")]
    ClientAttributes,
    #[sea_orm(has_many = "super::client_node_registrations::Entity")]
    ClientNodeRegistrations,
    #[sea_orm(has_many = "super::protocol_mapper::Entity")]
    ProtocolMapper,
    #[sea_orm(has_many = "super::redirect_uris::Entity")]
    RedirectUris,
    #[sea_orm(has_many = "super::scope_mapping::Entity")]
    ScopeMapping,
    #[sea_orm(has_many = "super::web_origins::Entity")]
    WebOrigins,
}

impl Related<super::client_attributes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ClientAttributes.def()
    }
}

impl Related<super::client_node_registrations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ClientNodeRegistrations.def()
    }
}

impl Related<super::protocol_mapper::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ProtocolMapper.def()
    }
}

impl Related<super::redirect_uris::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RedirectUris.def()
    }
}

impl Related<super::scope_mapping::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ScopeMapping.def()
    }
}

impl Related<super::web_origins::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::WebOrigins.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
