//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "client_scope")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub name: Option<String>,
    pub realm_id: Option<String>,
    pub description: Option<String>,
    pub protocol: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::client_scope_attributes::Entity")]
    ClientScopeAttributes,
    #[sea_orm(has_many = "super::client_scope_role_mapping::Entity")]
    ClientScopeRoleMapping,
    #[sea_orm(has_many = "super::protocol_mapper::Entity")]
    ProtocolMapper,
}

impl Related<super::client_scope_attributes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ClientScopeAttributes.def()
    }
}

impl Related<super::client_scope_role_mapping::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ClientScopeRoleMapping.def()
    }
}

impl Related<super::protocol_mapper::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ProtocolMapper.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
