//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "client_scope_role_mapping")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub scope_id: String,
    #[sea_orm(primary_key, auto_increment = false)]
    pub role_id: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::client_scope::Entity",
        from = "Column::ScopeId",
        to = "super::client_scope::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    ClientScope,
}

impl Related<super::client_scope::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ClientScope.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
