//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "composite_role")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub composite: String,
    #[sea_orm(primary_key, auto_increment = false)]
    pub child_role: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::keycloak_role::Entity",
        from = "Column::Composite",
        to = "super::keycloak_role::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    KeycloakRole2,
    #[sea_orm(
        belongs_to = "super::keycloak_role::Entity",
        from = "Column::ChildRole",
        to = "super::keycloak_role::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    KeycloakRole1,
}

impl ActiveModelBehavior for ActiveModel {}
