//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "databasechangelog")]
pub struct Model {
    pub id: String,
    pub author: String,
    pub filename: String,
    pub dateexecuted: DateTime,
    pub orderexecuted: i32,
    pub exectype: String,
    pub md5sum: Option<String>,
    pub description: Option<String>,
    pub comments: Option<String>,
    pub tag: Option<String>,
    pub liquibase: Option<String>,
    pub contexts: Option<String>,
    pub labels: Option<String>,
    pub deployment_id: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
