//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "event_entity")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub client_id: Option<String>,
    pub details_json: Option<String>,
    pub error: Option<String>,
    pub ip_address: Option<String>,
    pub realm_id: Option<String>,
    pub session_id: Option<String>,
    pub event_time: Option<i64>,
    pub r#type: Option<String>,
    pub user_id: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub details_json_long_value: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
