//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "fed_user_credential")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    #[sea_orm(column_type = "VarBinary(StringLen::None)", nullable)]
    pub salt: Option<Vec<u8>>,
    pub r#type: Option<String>,
    pub created_date: Option<i64>,
    pub user_id: String,
    pub realm_id: String,
    pub storage_provider_id: Option<String>,
    pub user_label: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub secret_data: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub credential_data: Option<String>,
    pub priority: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
