//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "fed_user_consent")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub client_id: Option<String>,
    pub user_id: String,
    pub realm_id: String,
    pub storage_provider_id: Option<String>,
    pub created_date: Option<i64>,
    pub last_updated_date: Option<i64>,
    pub client_storage_provider: Option<String>,
    pub external_client_id: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
