//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "fed_user_consent_cl_scope")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub user_consent_id: String,
    #[sea_orm(primary_key, auto_increment = false)]
    pub scope_id: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
