//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "group_attribute")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub name: String,
    pub value: Option<String>,
    pub group_id: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::keycloak_group::Entity",
        from = "Column::GroupId",
        to = "super::keycloak_group::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    KeycloakGroup,
}

impl Related<super::keycloak_group::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::KeycloakGroup.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
