//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "identity_provider")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub internal_id: String,
    pub enabled: bool,
    pub provider_alias: Option<String>,
    pub provider_id: Option<String>,
    pub store_token: bool,
    pub authenticate_by_default: bool,
    pub realm_id: Option<String>,
    pub add_token_role: bool,
    pub trust_email: bool,
    pub first_broker_login_flow_id: Option<String>,
    pub post_broker_login_flow_id: Option<String>,
    pub provider_display_name: Option<String>,
    pub link_only: bool,
    pub organization_id: Option<String>,
    pub hide_on_login: Option<bool>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::identity_provider_config::Entity")]
    IdentityProviderConfig,
    #[sea_orm(
        belongs_to = "super::realm::Entity",
        from = "Column::RealmId",
        to = "super::realm::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Realm,
}

impl Related<super::identity_provider_config::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::IdentityProviderConfig.def()
    }
}

impl Related<super::realm::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Realm.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
