//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "idp_mapper_config")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub idp_mapper_id: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub value: Option<String>,
    #[sea_orm(primary_key, auto_increment = false)]
    pub name: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::identity_provider_mapper::Entity",
        from = "Column::IdpMapperId",
        to = "super::identity_provider_mapper::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    IdentityProviderMapper,
}

impl Related<super::identity_provider_mapper::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::IdentityProviderMapper.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
