//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "keycloak_group")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub name: Option<String>,
    pub parent_group: String,
    pub realm_id: Option<String>,
    pub r#type: i32,
    pub description: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::group_attribute::Entity")]
    GroupAttribute,
    #[sea_orm(has_many = "super::group_role_mapping::Entity")]
    GroupRoleMapping,
}

impl Related<super::group_attribute::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::GroupAttribute.def()
    }
}

impl Related<super::group_role_mapping::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::GroupRoleMapping.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
