//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "keycloak_role")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub client_realm_constraint: Option<String>,
    pub client_role: bool,
    pub description: Option<String>,
    pub name: Option<String>,
    pub realm_id: Option<String>,
    pub client: Option<String>,
    pub realm: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::realm::Entity",
        from = "Column::Realm",
        to = "super::realm::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Realm,
    #[sea_orm(has_many = "super::role_attribute::Entity")]
    RoleAttribute,
}

impl Related<super::realm::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Realm.def()
    }
}

impl Related<super::role_attribute::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RoleAttribute.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
