//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "offline_user_session")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub user_session_id: String,
    pub user_id: String,
    pub realm_id: String,
    pub created_on: i32,
    #[sea_orm(primary_key, auto_increment = false)]
    pub offline_flag: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub data: Option<String>,
    pub last_session_refresh: i32,
    pub broker_session_id: Option<String>,
    pub version: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
