//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "offline_client_session")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub user_session_id: String,
    #[sea_orm(primary_key, auto_increment = false)]
    pub client_id: String,
    #[sea_orm(primary_key, auto_increment = false)]
    pub offline_flag: String,
    pub timestamp: Option<i32>,
    #[sea_orm(column_type = "Text", nullable)]
    pub data: Option<String>,
    #[sea_orm(primary_key, auto_increment = false)]
    pub client_storage_provider: String,
    #[sea_orm(primary_key, auto_increment = false)]
    pub external_client_id: String,
    pub version: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
