//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "protocol_mapper")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub name: String,
    pub protocol: String,
    pub protocol_mapper_name: String,
    pub client_id: Option<String>,
    pub client_scope_id: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::client::Entity",
        from = "Column::ClientId",
        to = "super::client::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Client,
    #[sea_orm(
        belongs_to = "super::client_scope::Entity",
        from = "Column::ClientScopeId",
        to = "super::client_scope::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    ClientScope,
    #[sea_orm(has_many = "super::protocol_mapper_config::Entity")]
    ProtocolMapperConfig,
}

impl Related<super::client::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Client.def()
    }
}

impl Related<super::client_scope::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ClientScope.def()
    }
}

impl Related<super::protocol_mapper_config::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ProtocolMapperConfig.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
