//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "realm_localizations")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub realm_id: String,
    #[sea_orm(primary_key, auto_increment = false)]
    pub locale: String,
    #[sea_orm(column_type = "Text")]
    pub texts: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
