//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "realm")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub access_code_lifespan: Option<i32>,
    pub user_action_lifespan: Option<i32>,
    pub access_token_lifespan: Option<i32>,
    pub account_theme: Option<String>,
    pub admin_theme: Option<String>,
    pub email_theme: Option<String>,
    pub enabled: bool,
    pub events_enabled: bool,
    pub events_expiration: Option<i64>,
    pub login_theme: Option<String>,
    #[sea_orm(unique)]
    pub name: Option<String>,
    pub not_before: Option<i32>,
    pub password_policy: Option<String>,
    pub registration_allowed: bool,
    pub remember_me: bool,
    pub reset_password_allowed: bool,
    pub social: bool,
    pub ssl_required: Option<String>,
    pub sso_idle_timeout: Option<i32>,
    pub sso_max_lifespan: Option<i32>,
    pub update_profile_on_soc_login: bool,
    pub verify_email: bool,
    pub master_admin_client: Option<String>,
    pub login_lifespan: Option<i32>,
    pub internationalization_enabled: bool,
    pub default_locale: Option<String>,
    pub reg_email_as_username: bool,
    pub admin_events_enabled: bool,
    pub admin_events_details_enabled: bool,
    pub edit_username_allowed: bool,
    pub otp_policy_counter: Option<i32>,
    pub otp_policy_window: Option<i32>,
    pub otp_policy_period: Option<i32>,
    pub otp_policy_digits: Option<i32>,
    pub otp_policy_alg: Option<String>,
    pub otp_policy_type: Option<String>,
    pub browser_flow: Option<String>,
    pub registration_flow: Option<String>,
    pub direct_grant_flow: Option<String>,
    pub reset_credentials_flow: Option<String>,
    pub client_auth_flow: Option<String>,
    pub offline_session_idle_timeout: Option<i32>,
    pub revoke_refresh_token: bool,
    pub access_token_life_implicit: Option<i32>,
    pub login_with_email_allowed: bool,
    pub duplicate_emails_allowed: bool,
    pub docker_auth_flow: Option<String>,
    pub refresh_token_max_reuse: Option<i32>,
    pub allow_user_managed_access: bool,
    pub sso_max_lifespan_remember_me: i32,
    pub sso_idle_timeout_remember_me: i32,
    pub default_role: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::authentication_execution::Entity")]
    AuthenticationExecution,
    #[sea_orm(has_many = "super::authentication_flow::Entity")]
    AuthenticationFlow,
    #[sea_orm(has_many = "super::authenticator_config::Entity")]
    AuthenticatorConfig,
    #[sea_orm(has_many = "super::client_initial_access::Entity")]
    ClientInitialAccess,
    #[sea_orm(has_many = "super::component::Entity")]
    Component,
    #[sea_orm(has_many = "super::default_client_scope::Entity")]
    DefaultClientScope,
    #[sea_orm(has_many = "super::identity_provider::Entity")]
    IdentityProvider,
    #[sea_orm(has_many = "super::identity_provider_mapper::Entity")]
    IdentityProviderMapper,
    #[sea_orm(has_many = "super::keycloak_role::Entity")]
    KeycloakRole,
    #[sea_orm(has_many = "super::realm_attribute::Entity")]
    RealmAttribute,
    #[sea_orm(has_many = "super::realm_default_groups::Entity")]
    RealmDefaultGroups,
    #[sea_orm(has_many = "super::realm_enabled_event_types::Entity")]
    RealmEnabledEventTypes,
    #[sea_orm(has_many = "super::realm_events_listeners::Entity")]
    RealmEventsListeners,
    #[sea_orm(has_many = "super::realm_required_credential::Entity")]
    RealmRequiredCredential,
    #[sea_orm(has_many = "super::realm_smtp_config::Entity")]
    RealmSmtpConfig,
    #[sea_orm(has_many = "super::realm_supported_locales::Entity")]
    RealmSupportedLocales,
    #[sea_orm(has_many = "super::required_action_provider::Entity")]
    RequiredActionProvider,
    #[sea_orm(has_many = "super::user_federation_mapper::Entity")]
    UserFederationMapper,
    #[sea_orm(has_many = "super::user_federation_provider::Entity")]
    UserFederationProvider,
}

impl Related<super::authentication_execution::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AuthenticationExecution.def()
    }
}

impl Related<super::authentication_flow::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AuthenticationFlow.def()
    }
}

impl Related<super::authenticator_config::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AuthenticatorConfig.def()
    }
}

impl Related<super::client_initial_access::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ClientInitialAccess.def()
    }
}

impl Related<super::component::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Component.def()
    }
}

impl Related<super::default_client_scope::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DefaultClientScope.def()
    }
}

impl Related<super::identity_provider::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::IdentityProvider.def()
    }
}

impl Related<super::identity_provider_mapper::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::IdentityProviderMapper.def()
    }
}

impl Related<super::keycloak_role::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::KeycloakRole.def()
    }
}

impl Related<super::realm_attribute::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RealmAttribute.def()
    }
}

impl Related<super::realm_default_groups::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RealmDefaultGroups.def()
    }
}

impl Related<super::realm_enabled_event_types::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RealmEnabledEventTypes.def()
    }
}

impl Related<super::realm_events_listeners::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RealmEventsListeners.def()
    }
}

impl Related<super::realm_required_credential::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RealmRequiredCredential.def()
    }
}

impl Related<super::realm_smtp_config::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RealmSmtpConfig.def()
    }
}

impl Related<super::realm_supported_locales::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RealmSupportedLocales.def()
    }
}

impl Related<super::required_action_provider::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RequiredActionProvider.def()
    }
}

impl Related<super::user_federation_mapper::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserFederationMapper.def()
    }
}

impl Related<super::user_federation_provider::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserFederationProvider.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
