//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "resource_server_scope")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub name: String,
    pub icon_uri: Option<String>,
    pub resource_server_id: String,
    pub display_name: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::resource_scope::Entity")]
    ResourceScope,
    #[sea_orm(
        belongs_to = "super::resource_server::Entity",
        from = "Column::ResourceServerId",
        to = "super::resource_server::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    ResourceServer,
    #[sea_orm(has_many = "super::resource_server_perm_ticket::Entity")]
    ResourceServerPermTicket,
    #[sea_orm(has_many = "super::scope_policy::Entity")]
    ScopePolicy,
}

impl Related<super::resource_scope::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ResourceScope.def()
    }
}

impl Related<super::resource_server::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ResourceServer.def()
    }
}

impl Related<super::resource_server_perm_ticket::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ResourceServerPermTicket.def()
    }
}

impl Related<super::scope_policy::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ScopePolicy.def()
    }
}

impl Related<super::resource_server_policy::Entity> for Entity {
    fn to() -> RelationDef {
        super::scope_policy::Relation::ResourceServerPolicy.def()
    }
    fn via() -> Option<RelationDef> {
        Some(
            super::scope_policy::Relation::ResourceServerScope
                .def()
                .rev(),
        )
    }
}

impl Related<super::resource_server_resource::Entity> for Entity {
    fn to() -> RelationDef {
        super::resource_scope::Relation::ResourceServerResource.def()
    }
    fn via() -> Option<RelationDef> {
        Some(
            super::resource_scope::Relation::ResourceServerScope
                .def()
                .rev(),
        )
    }
}

impl ActiveModelBehavior for ActiveModel {}
