//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "resource_server_perm_ticket")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub owner: String,
    pub requester: String,
    pub created_timestamp: i64,
    pub granted_timestamp: Option<i64>,
    pub resource_id: String,
    pub scope_id: Option<String>,
    pub resource_server_id: String,
    pub policy_id: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::resource_server::Entity",
        from = "Column::ResourceServerId",
        to = "super::resource_server::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    ResourceServer,
    #[sea_orm(
        belongs_to = "super::resource_server_policy::Entity",
        from = "Column::PolicyId",
        to = "super::resource_server_policy::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    ResourceServerPolicy,
    #[sea_orm(
        belongs_to = "super::resource_server_resource::Entity",
        from = "Column::ResourceId",
        to = "super::resource_server_resource::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    ResourceServerResource,
    #[sea_orm(
        belongs_to = "super::resource_server_scope::Entity",
        from = "Column::ScopeId",
        to = "super::resource_server_scope::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    ResourceServerScope,
}

impl Related<super::resource_server::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ResourceServer.def()
    }
}

impl Related<super::resource_server_policy::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ResourceServerPolicy.def()
    }
}

impl Related<super::resource_server_resource::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ResourceServerResource.def()
    }
}

impl Related<super::resource_server_scope::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ResourceServerScope.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
