//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "resource_server")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub allow_rs_remote_mgmt: bool,
    pub policy_enforce_mode: i16,
    pub decision_strategy: i16,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::resource_server_perm_ticket::Entity")]
    ResourceServerPermTicket,
    #[sea_orm(has_many = "super::resource_server_policy::Entity")]
    ResourceServerPolicy,
    #[sea_orm(has_many = "super::resource_server_resource::Entity")]
    ResourceServerResource,
    #[sea_orm(has_many = "super::resource_server_scope::Entity")]
    ResourceServerScope,
}

impl Related<super::resource_server_perm_ticket::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ResourceServerPermTicket.def()
    }
}

impl Related<super::resource_server_policy::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ResourceServerPolicy.def()
    }
}

impl Related<super::resource_server_resource::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ResourceServerResource.def()
    }
}

impl Related<super::resource_server_scope::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ResourceServerScope.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
