//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "resource_policy")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub resource_id: String,
    #[sea_orm(primary_key, auto_increment = false)]
    pub policy_id: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::resource_server_policy::Entity",
        from = "Column::PolicyId",
        to = "super::resource_server_policy::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    ResourceServerPolicy,
    #[sea_orm(
        belongs_to = "super::resource_server_resource::Entity",
        from = "Column::ResourceId",
        to = "super::resource_server_resource::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    ResourceServerResource,
}

impl Related<super::resource_server_policy::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ResourceServerPolicy.def()
    }
}

impl Related<super::resource_server_resource::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ResourceServerResource.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
