//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "role_attribute")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub role_id: String,
    pub name: String,
    pub value: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::keycloak_role::Entity",
        from = "Column::RoleId",
        to = "super::keycloak_role::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    KeycloakRole,
}

impl Related<super::keycloak_role::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::KeycloakRole.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
