//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "scope_policy")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub scope_id: String,
    #[sea_orm(primary_key, auto_increment = false)]
    pub policy_id: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::resource_server_policy::Entity",
        from = "Column::PolicyId",
        to = "super::resource_server_policy::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    ResourceServerPolicy,
    #[sea_orm(
        belongs_to = "super::resource_server_scope::Entity",
        from = "Column::ScopeId",
        to = "super::resource_server_scope::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    ResourceServerScope,
}

impl Related<super::resource_server_policy::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ResourceServerPolicy.def()
    }
}

impl Related<super::resource_server_scope::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ResourceServerScope.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
