//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "user_attribute")]
pub struct Model {
    pub name: String,
    pub value: Option<String>,
    pub user_id: String,
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    #[sea_orm(column_type = "VarBinary(StringLen::None)", nullable)]
    pub long_value_hash: Option<Vec<u8>>,
    #[sea_orm(column_type = "VarBinary(StringLen::None)", nullable)]
    pub long_value_hash_lower_case: Option<Vec<u8>>,
    #[sea_orm(column_type = "Text", nullable)]
    pub long_value: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::user_entity::Entity",
        from = "Column::UserId",
        to = "super::user_entity::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    UserEntity,
}

impl Related<super::user_entity::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserEntity.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
