//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "user_federation_provider")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub changed_sync_period: Option<i32>,
    pub display_name: Option<String>,
    pub full_sync_period: Option<i32>,
    pub last_sync: Option<i32>,
    pub priority: Option<i32>,
    pub provider_name: Option<String>,
    pub realm_id: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::realm::Entity",
        from = "Column::RealmId",
        to = "super::realm::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Realm,
    #[sea_orm(has_many = "super::user_federation_config::Entity")]
    UserFederationConfig,
    #[sea_orm(has_many = "super::user_federation_mapper::Entity")]
    UserFederationMapper,
}

impl Related<super::realm::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Realm.def()
    }
}

impl Related<super::user_federation_config::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserFederationConfig.def()
    }
}

impl Related<super::user_federation_mapper::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserFederationMapper.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
