//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "user_consent_client_scope")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub user_consent_id: String,
    #[sea_orm(primary_key, auto_increment = false)]
    pub scope_id: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::user_consent::Entity",
        from = "Column::UserConsentId",
        to = "super::user_consent::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    UserConsent,
}

impl Related<super::user_consent::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserConsent.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
