//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "user_consent")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub client_id: Option<String>,
    pub user_id: String,
    pub created_date: Option<i64>,
    pub last_updated_date: Option<i64>,
    pub client_storage_provider: Option<String>,
    pub external_client_id: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::user_consent_client_scope::Entity")]
    UserConsentClientScope,
    #[sea_orm(
        belongs_to = "super::user_entity::Entity",
        from = "Column::UserId",
        to = "super::user_entity::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    UserEntity,
}

impl Related<super::user_consent_client_scope::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserConsentClientScope.def()
    }
}

impl Related<super::user_entity::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserEntity.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
