//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "user_federation_config")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub user_federation_provider_id: String,
    pub value: Option<String>,
    #[sea_orm(primary_key, auto_increment = false)]
    pub name: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::user_federation_provider::Entity",
        from = "Column::UserFederationProviderId",
        to = "super::user_federation_provider::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    UserFederationProvider,
}

impl Related<super::user_federation_provider::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserFederationProvider.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
