//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "user_federation_mapper")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub name: String,
    pub federation_provider_id: String,
    pub federation_mapper_type: String,
    pub realm_id: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::realm::Entity",
        from = "Column::RealmId",
        to = "super::realm::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Realm,
    #[sea_orm(has_many = "super::user_federation_mapper_config::Entity")]
    UserFederationMapperConfig,
    #[sea_orm(
        belongs_to = "super::user_federation_provider::Entity",
        from = "Column::FederationProviderId",
        to = "super::user_federation_provider::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    UserFederationProvider,
}

impl Related<super::realm::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Realm.def()
    }
}

impl Related<super::user_federation_mapper_config::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserFederationMapperConfig.def()
    }
}

impl Related<super::user_federation_provider::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserFederationProvider.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
