//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "user_entity")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub email: Option<String>,
    pub email_constraint: Option<String>,
    pub email_verified: bool,
    pub enabled: bool,
    pub federation_link: Option<String>,
    pub first_name: Option<String>,
    pub last_name: Option<String>,
    pub realm_id: Option<String>,
    pub username: Option<String>,
    pub created_timestamp: Option<i64>,
    pub service_account_client_link: Option<String>,
    pub not_before: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::credential::Entity")]
    Credential,
    #[sea_orm(has_many = "super::federated_identity::Entity")]
    FederatedIdentity,
    #[sea_orm(has_many = "super::user_attribute::Entity")]
    UserAttribute,
    #[sea_orm(has_many = "super::user_consent::Entity")]
    UserConsent,
    #[sea_orm(has_many = "super::user_group_membership::Entity")]
    UserGroupMembership,
    #[sea_orm(has_many = "super::user_required_action::Entity")]
    UserRequiredAction,
    #[sea_orm(has_many = "super::user_role_mapping::Entity")]
    UserRoleMapping,
}

impl Related<super::credential::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Credential.def()
    }
}

impl Related<super::federated_identity::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FederatedIdentity.def()
    }
}

impl Related<super::user_attribute::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserAttribute.def()
    }
}

impl Related<super::user_consent::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserConsent.def()
    }
}

impl Related<super::user_group_membership::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserGroupMembership.def()
    }
}

impl Related<super::user_required_action::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserRequiredAction.def()
    }
}

impl Related<super::user_role_mapping::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserRoleMapping.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
