INSERT INTO authz.role_definition (role_key, role_name, role_scope, stage_from, description) VALUES
('crosschain_admin', '跨链管理员', 'platform', 'V3', '跨链请求治理'),
('witness_admin', '见证人/预言机管理员', 'platform', 'V3', '见证配置与签名治理'),
('mutual_recognition_admin', '数据空间互认管理员', 'platform', 'V3', '互认关系维护'),
('graph_risk_operator', '图风控运营角色', 'platform', 'V3', '图风控分析与处置'),
('regulatory_collab_admin', '监管协同管理员', 'platform', 'V3', '监管协同与冻结联动'),
('ecosystem_admin', '生态合作管理员', 'platform', 'V3', '生态合作与伙伴能力开放'),
('connector_admin', '连接器管理员', 'platform', 'V3', '连接器接入管理'),
('cross_platform_trust_admin', '跨平台信任管理员', 'platform', 'V3', '跨平台托管与信任边界治理'),
('digital_asset_settlement_admin', '数字资产结算管理员', 'platform', 'V3', '多币种、跨境与数字资产结算治理'),
('regulator_operator', '监管协同操作员', 'regulator', 'V3', '监管查询与协同操作')
ON CONFLICT (role_key) DO NOTHING;

INSERT INTO authz.permission_definition (permission_code, domain_name, resource_name, action_name, stage_from, risk_level) VALUES
('crosschain.request.create','crosschain','request','create','V3','high'),
('crosschain.request.read','crosschain','request','read','V3','normal'),
('crosschain.request.retry','crosschain','request','retry','V3','high'),
('crosschain.request.terminate','crosschain','request','terminate','V3','high'),
('crosschain.request.compensate','crosschain','request','compensate','V3','high'),
('crosschain.ack.read','crosschain','ack','read','V3','normal'),
('crosschain.witness.manage','crosschain','witness','manage','V3','high'),
('risk.graph.read','risk','graph','read','V3','normal'),
('risk.graph.analyze','risk','graph','analyze','V3','medium'),
('risk.alert.read','risk','alert','read','V3','normal'),
('risk.case.create','risk','case','create','V3','medium'),
('risk.case.review','risk','case','review','V3','high'),
('risk.freeze.execute','risk','freeze','execute','V3','high'),
('risk.freeze.release','risk','freeze','release','V3','high'),
('regulator.query.order','regulator','query','order','V3','medium'),
('regulator.query.subject','regulator','query','subject','V3','medium'),
('regulator.query.asset','regulator','query','asset','V3','medium'),
('regulator.package.export','regulator','package','export','V3','high'),
('regulator.freeze.request','regulator','freeze','request','V3','high'),
('regulator.storage_trace.read','regulator','storage_trace','read','V3','medium'),
('ecosystem.connector.apply','ecosystem','connector','apply','V3','medium'),
('ecosystem.connector.review','ecosystem','connector','review','V3','high'),
('ecosystem.connector.manage','ecosystem','connector','manage','V3','high'),
('ecosystem.partner.read','ecosystem','partner','read','V3','normal'),
('ecosystem.partner.manage','ecosystem','partner','manage','V3','high'),
('ecosystem.mutual_recognition.manage','ecosystem','mutual_recognition','manage','V3','high'),
('ecosystem.trust_boundary.manage','ecosystem','trust_boundary','manage','V3','high'),
('payment.route.manage','payment','route','manage','V3','high'),
('payment.fx_quote.read','payment','fx_quote','read','V3','medium'),
('payment.crypto_transfer.read','payment','crypto_transfer','read','V3','medium'),
('payment.crypto_transfer.execute','payment','crypto_transfer','execute','V3','high'),
('iam.federation.manage','iam','federation','manage','V3','high'),
('iam.risk_auth.manage','iam','risk_auth','manage','V3','high'),
('ops.recommend_page_optimize.manage','ops','recommend_page_optimize','manage','V3','high'),
('ops.recommend_ecosystem.manage','ops','recommend_ecosystem','manage','V3','high'),
('developer.crosschain_trace.read','developer','crosschain_trace','read','V3','normal'),
('developer.risk_sample.read','developer','risk_sample','read','V3','normal'),
('developer.regulator_sandbox.read','developer','regulator_sandbox','read','V3','normal')
ON CONFLICT (permission_code) DO NOTHING;
