-- V3 不新增一级核心角色，新增职责通过 V1 已冻结的核心角色挂载权限包承接。

INSERT INTO authz.permission_definition (permission_code, domain_name, resource_name, action_name, stage_from, risk_level) VALUES
('crosschain.request.create','crosschain','request','create','V3','high'),
('crosschain.request.read','crosschain','request','read','V3','normal'),
('crosschain.request.retry','crosschain','request','retry','V3','high'),
('crosschain.request.terminate','crosschain','request','terminate','V3','high'),
('crosschain.request.compensate','crosschain','request','compensate','V3','high'),
('crosschain.ack.read','crosschain','ack','read','V3','normal'),
('crosschain.witness.manage','crosschain','witness','manage','V3','high'),
('risk.graph.read','risk','graph','read','V3','normal'),
('risk.graph.analyze','risk','graph','analyze','V3','medium'),
('risk.alert.read','risk','alert','read','V3','normal'),
('risk.case.create','risk','case','create','V3','medium'),
('risk.case.review','risk','case','review','V3','high'),
('risk.freeze.execute','risk','freeze','execute','V3','high'),
('risk.freeze.release','risk','freeze','release','V3','high'),
('regulator.query.order','regulator','query','order','V3','medium'),
('regulator.query.subject','regulator','query','subject','V3','medium'),
('regulator.query.asset','regulator','query','asset','V3','medium'),
('regulator.package.export','regulator','package','export','V3','high'),
('regulator.freeze.request','regulator','freeze','request','V3','high'),
('regulator.storage_trace.read','regulator','storage_trace','read','V3','medium'),
('ecosystem.connector.apply','ecosystem','connector','apply','V3','medium'),
('ecosystem.connector.review','ecosystem','connector','review','V3','high'),
('ecosystem.connector.manage','ecosystem','connector','manage','V3','high'),
('ecosystem.partner.read','ecosystem','partner','read','V3','normal'),
('ecosystem.partner.manage','ecosystem','partner','manage','V3','high'),
('ecosystem.mutual_recognition.manage','ecosystem','mutual_recognition','manage','V3','high'),
('ecosystem.trust_boundary.manage','ecosystem','trust_boundary','manage','V3','high'),
('payment.route.manage','payment','route','manage','V3','high'),
('payment.fx_quote.read','payment','fx_quote','read','V3','medium'),
('payment.crypto_transfer.read','payment','crypto_transfer','read','V3','medium'),
('payment.crypto_transfer.execute','payment','crypto_transfer','execute','V3','high'),
('iam.federation.manage','iam','federation','manage','V3','high'),
('iam.risk_auth.manage','iam','risk_auth','manage','V3','high'),
('ops.recommend_page_optimize.manage','ops','recommend_page_optimize','manage','V3','high'),
('ops.recommend_ecosystem.manage','ops','recommend_ecosystem','manage','V3','high'),
('developer.crosschain_trace.read','developer','crosschain_trace','read','V3','normal'),
('developer.risk_sample.read','developer','risk_sample','read','V3','normal'),
('developer.regulator_sandbox.read','developer','regulator_sandbox','read','V3','normal')
ON CONFLICT (permission_code) DO NOTHING;
