#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"
source "${REPO_ROOT}/scripts/fabric-env.sh"

"${REPO_ROOT}/infra/fabric/install-deps.sh"

if [[ ! -d "${FABRIC_TEST_NETWORK_ROOT}" ]]; then
  echo "fabric test-network root not found: ${FABRIC_TEST_NETWORK_ROOT}" >&2
  exit 1
fi

if [[ ! -d "${FABRIC_CHAINCODE_PATH}" ]]; then
  echo "fabric chaincode path not found: ${FABRIC_CHAINCODE_PATH}" >&2
  exit 1
fi

pushd "${FABRIC_TEST_NETWORK_ROOT}" >/dev/null
./network.sh deployCC \
  -ca \
  -c "${FABRIC_CHANNEL_NAME}" \
  -ccn "${FABRIC_CHAINCODE_NAME}" \
  -ccp "${FABRIC_CHAINCODE_PATH}" \
  -ccl go \
  -ccv "${FABRIC_CHAINCODE_VERSION}" \
  -ccs "${FABRIC_CHAINCODE_SEQUENCE}"
popd >/dev/null

cat > "${FABRIC_STATE_DIR}/runtime.env" <<EOF
FABRIC_VERSION=${FABRIC_VERSION}
FABRIC_CA_VERSION=${FABRIC_CA_VERSION}
FABRIC_NETWORK_NAME=${FABRIC_NETWORK_NAME}
FABRIC_CHANNEL_NAME=${FABRIC_CHANNEL_NAME}
FABRIC_CHAINCODE_NAME=${FABRIC_CHAINCODE_NAME}
FABRIC_CHAINCODE_VERSION=${FABRIC_CHAINCODE_VERSION}
FABRIC_CHAINCODE_SEQUENCE=${FABRIC_CHAINCODE_SEQUENCE}
FABRIC_GATEWAY_ENDPOINT=${FABRIC_GATEWAY_ENDPOINT}
FABRIC_GATEWAY_PEER=${FABRIC_GATEWAY_PEER}
FABRIC_MSP_ID=${FABRIC_MSP_ID}
FABRIC_TLS_CERT_PATH=${FABRIC_TLS_CERT_PATH}
FABRIC_SIGN_CERT_PATH=${FABRIC_SIGN_CERT_PATH}
FABRIC_PRIVATE_KEY_PATH=${FABRIC_PRIVATE_KEY_PATH}
FABRIC_CHAINCODE_PATH=${FABRIC_CHAINCODE_PATH}
EOF

echo "[done] deployed chaincode ${FABRIC_CHAINCODE_NAME} on channel ${FABRIC_CHANNEL_NAME}"
