#!/usr/bin/env bash
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
source "${REPO_ROOT}/scripts/go-env.sh"

preserve_env_var() {
  local name="${1}"
  if [[ -n "${!name+x}" ]]; then
    printf '%s' "${!name}"
  fi
}

FABRIC_ADAPTER_PROVIDER_MODE_OVERRIDE="$(preserve_env_var FABRIC_ADAPTER_PROVIDER_MODE)"
FABRIC_ADAPTER_CONSUMER_GROUP_OVERRIDE="$(preserve_env_var FABRIC_ADAPTER_CONSUMER_GROUP)"
FABRIC_ADAPTER_CONSUMER_LOCK_TTL_OVERRIDE="$(preserve_env_var FABRIC_ADAPTER_CONSUMER_LOCK_TTL)"
KAFKA_BROKERS_OVERRIDE="$(preserve_env_var KAFKA_BROKERS)"
DATABASE_URL_OVERRIDE="$(preserve_env_var DATABASE_URL)"
REDIS_URL_OVERRIDE="$(preserve_env_var REDIS_URL)"
REDIS_NAMESPACE_OVERRIDE="$(preserve_env_var REDIS_NAMESPACE)"
TOPIC_AUDIT_ANCHOR_OVERRIDE="$(preserve_env_var TOPIC_AUDIT_ANCHOR)"
TOPIC_FABRIC_REQUESTS_OVERRIDE="$(preserve_env_var TOPIC_FABRIC_REQUESTS)"
FABRIC_GATEWAY_ENDPOINT_OVERRIDE="$(preserve_env_var FABRIC_GATEWAY_ENDPOINT)"
FABRIC_GATEWAY_PEER_OVERRIDE="$(preserve_env_var FABRIC_GATEWAY_PEER)"
FABRIC_MSP_ID_OVERRIDE="$(preserve_env_var FABRIC_MSP_ID)"
FABRIC_TLS_CERT_PATH_OVERRIDE="$(preserve_env_var FABRIC_TLS_CERT_PATH)"
FABRIC_SIGN_CERT_PATH_OVERRIDE="$(preserve_env_var FABRIC_SIGN_CERT_PATH)"
FABRIC_PRIVATE_KEY_DIR_OVERRIDE="$(preserve_env_var FABRIC_PRIVATE_KEY_DIR)"
FABRIC_PRIVATE_KEY_PATH_OVERRIDE="$(preserve_env_var FABRIC_PRIVATE_KEY_PATH)"

if [[ -f "${REPO_ROOT}/infra/docker/.env.local" ]]; then
  set -a
  # shellcheck disable=SC1091
  source "${REPO_ROOT}/infra/docker/.env.local"
  set +a
fi
source "${REPO_ROOT}/scripts/fabric-env.sh"

if [[ -n "${FABRIC_ADAPTER_PROVIDER_MODE_OVERRIDE}" ]]; then
  export FABRIC_ADAPTER_PROVIDER_MODE="${FABRIC_ADAPTER_PROVIDER_MODE_OVERRIDE}"
fi
if [[ -n "${FABRIC_ADAPTER_CONSUMER_GROUP_OVERRIDE}" ]]; then
  export FABRIC_ADAPTER_CONSUMER_GROUP="${FABRIC_ADAPTER_CONSUMER_GROUP_OVERRIDE}"
fi
if [[ -n "${FABRIC_ADAPTER_CONSUMER_LOCK_TTL_OVERRIDE}" ]]; then
  export FABRIC_ADAPTER_CONSUMER_LOCK_TTL="${FABRIC_ADAPTER_CONSUMER_LOCK_TTL_OVERRIDE}"
fi
if [[ -n "${KAFKA_BROKERS_OVERRIDE}" ]]; then
  export KAFKA_BROKERS="${KAFKA_BROKERS_OVERRIDE}"
fi
if [[ -n "${DATABASE_URL_OVERRIDE}" ]]; then
  export DATABASE_URL="${DATABASE_URL_OVERRIDE}"
fi
if [[ -n "${REDIS_URL_OVERRIDE}" ]]; then
  export REDIS_URL="${REDIS_URL_OVERRIDE}"
fi
if [[ -n "${REDIS_NAMESPACE_OVERRIDE}" ]]; then
  export REDIS_NAMESPACE="${REDIS_NAMESPACE_OVERRIDE}"
fi
if [[ -n "${TOPIC_AUDIT_ANCHOR_OVERRIDE}" ]]; then
  export TOPIC_AUDIT_ANCHOR="${TOPIC_AUDIT_ANCHOR_OVERRIDE}"
fi
if [[ -n "${TOPIC_FABRIC_REQUESTS_OVERRIDE}" ]]; then
  export TOPIC_FABRIC_REQUESTS="${TOPIC_FABRIC_REQUESTS_OVERRIDE}"
fi
if [[ -n "${FABRIC_GATEWAY_ENDPOINT_OVERRIDE}" ]]; then
  export FABRIC_GATEWAY_ENDPOINT="${FABRIC_GATEWAY_ENDPOINT_OVERRIDE}"
fi
if [[ -n "${FABRIC_GATEWAY_PEER_OVERRIDE}" ]]; then
  export FABRIC_GATEWAY_PEER="${FABRIC_GATEWAY_PEER_OVERRIDE}"
fi
if [[ -n "${FABRIC_MSP_ID_OVERRIDE}" ]]; then
  export FABRIC_MSP_ID="${FABRIC_MSP_ID_OVERRIDE}"
fi
if [[ -n "${FABRIC_TLS_CERT_PATH_OVERRIDE}" ]]; then
  export FABRIC_TLS_CERT_PATH="${FABRIC_TLS_CERT_PATH_OVERRIDE}"
fi
if [[ -n "${FABRIC_SIGN_CERT_PATH_OVERRIDE}" ]]; then
  export FABRIC_SIGN_CERT_PATH="${FABRIC_SIGN_CERT_PATH_OVERRIDE}"
fi
if [[ -n "${FABRIC_PRIVATE_KEY_DIR_OVERRIDE}" ]]; then
  export FABRIC_PRIVATE_KEY_DIR="${FABRIC_PRIVATE_KEY_DIR_OVERRIDE}"
fi
if [[ -n "${FABRIC_PRIVATE_KEY_PATH_OVERRIDE}" ]]; then
  export FABRIC_PRIVATE_KEY_PATH="${FABRIC_PRIVATE_KEY_PATH_OVERRIDE}"
fi

export KAFKA_BROKERS="${KAFKA_BROKERS:-${KAFKA_BOOTSTRAP_SERVERS:-127.0.0.1:${KAFKA_EXTERNAL_PORT:-9094}}}"
export DATABASE_URL="${DATABASE_URL:-postgres://datab:datab_local_pass@127.0.0.1:5432/datab}"
export REDIS_URL="${REDIS_URL:-redis://:${REDIS_PASSWORD:-datab_redis_pass}@127.0.0.1:${REDIS_PORT:-6379}/4}"
export REDIS_NAMESPACE="${REDIS_NAMESPACE:-datab:v1}"
export FABRIC_ADAPTER_CONSUMER_LOCK_TTL="${FABRIC_ADAPTER_CONSUMER_LOCK_TTL:-15s}"

pushd "${REPO_ROOT}/services/fabric-adapter" >/dev/null
go run ./cmd/fabric-adapter
popd >/dev/null
