INSERT INTO authz.role_definition (role_key, role_name, role_scope, stage_from, description) VALUES
('platform_super_admin', '平台超级管理员', 'platform', 'V1', '系统最高管理角色'),
('subject_reviewer', '主体审核员', 'platform', 'V1', '主体准入审核'),
('product_reviewer', '产品审核员', 'platform', 'V1', '商品审核'),
('compliance_reviewer', '合规审核员', 'platform', 'V1', '合规审查'),
('risk_operator', '风控专员', 'platform', 'V1', '风险处置'),
('finance_operator', '财务结算专员', 'platform', 'V1', '账单和赔付'),
('payment_channel_admin', '支付渠道管理员', 'platform', 'V1', '支付渠道、商户与回调配置'),
('pricing_admin', '定价与收费管理员', 'platform', 'V1', '收费规则与参数治理'),
('reconciliation_operator', '对账专员', 'platform', 'V1', '渠道账单导入与差异处理'),
('dispute_operator', '争议处理专员', 'platform', 'V1', '争议裁决'),
('audit_admin', '审计管理员', 'platform', 'V1', '审计与证据'),
('data_custody_admin', '数据托管管理员', 'platform', 'V1', '托管对象与生命周期策略治理'),
('key_custody_admin', '密钥托管管理员', 'platform', 'V1', '密钥封装与解密边界治理'),
('tenant_admin', 'Tenant 管理员', 'tenant', 'V1', '租户内管理'),
('data_governance_admin', '数据治理管理员', 'tenant', 'V1', '商品与元数据管理'),
('listing_manager', '产品经理/上架管理员', 'tenant', 'V1', '商品上架'),
('seller_storage_operator', '卖方存储运营员', 'tenant', 'V1', '卖方自持存储与交付工单维护'),
('retention_admin', '数据保留与销毁管理员', 'tenant', 'V1', '保留与销毁策略治理'),
('procurement_manager', '采购经理', 'tenant', 'V1', '下单与验收'),
('finance_manager', '财务经理', 'tenant', 'V1', '账单查看'),
('developer_admin', '开发者/应用管理员', 'tenant', 'V1', '测试应用与调试'),
('business_analyst', '业务分析师/查询使用者', 'tenant', 'V1', '使用数据能力'),
('regulator_observer', '监管观察员', 'regulator', 'V1', '只读监管视图')
ON CONFLICT (role_key) DO NOTHING;

INSERT INTO authz.permission_definition (permission_code, domain_name, resource_name, action_name, stage_from, risk_level) VALUES
('portal.home.read','portal','home','read','V1','normal'),
('portal.industry_topic.read','portal','industry_topic','read','V1','normal'),
('portal.search.read','portal','search','read','V1','normal'),
('portal.search.use','portal','search','use','V1','normal'),
('catalog.product.list','catalog','product','list','V1','normal'),
('catalog.product.read','catalog','product','read','V1','normal'),
('catalog.sample.read','catalog','sample','read','V1','normal'),
('catalog.public_verify.read','catalog','public_verify','read','V1','normal'),
('catalog.asset.create','catalog','asset','create','V1','normal'),
('catalog.asset.update','catalog','asset','update','V1','normal'),
('catalog.asset_version.create','catalog','asset_version','create','V1','normal'),
('catalog.custody.manage','catalog','custody','manage','V1','medium'),
('catalog.storage_binding.manage','catalog','storage_binding','manage','V1','medium'),
('catalog.trust_evidence.read','catalog','trust_evidence','read','V1','normal'),
('catalog.trust_evidence.upload','catalog','trust_evidence','upload','V1','medium'),
('catalog.product.create','catalog','product','create','V1','normal'),
('catalog.product.update','catalog','product','update','V1','normal'),
('catalog.product.submit','catalog','product','submit','V1','normal'),
('catalog.product.suspend','catalog','product','suspend','V1','medium'),
('catalog.product.retire','catalog','product','retire','V1','medium'),
('catalog.sku.read','catalog','sku','read','V1','normal'),
('catalog.sku.create','catalog','sku','create','V1','normal'),
('catalog.sku.update','catalog','sku','update','V1','normal'),
('catalog.sample.upload','catalog','sample','upload','V1','normal'),
('catalog.metadata.edit','catalog','metadata','edit','V1','normal'),
('template.contract.read','template','contract','read','V1','normal'),
('template.contract.bind','template','contract','bind','V1','normal'),
('template.contract.manage','template','contract','manage','V1','medium'),
('template.acceptance.read','template','acceptance','read','V1','normal'),
('template.acceptance.bind','template','acceptance','bind','V1','normal'),
('template.refund.read','template','refund','read','V1','normal'),
('template.refund.bind','template','refund','bind','V1','normal'),
('template.billing.read','template','billing','read','V1','normal'),
('template.billing.bind','template','billing','bind','V1','normal'),
('template.policy.bind','template','policy','bind','V1','normal'),
('template.policy.read','template','policy','read','V1','normal'),
('template.policy.update','template','policy','update','V1','medium'),
('trade.inquiry.create','trade','inquiry','create','V1','normal'),
('trade.order.create','trade','order','create','V1','normal'),
('trade.order.read','trade','order','read','V1','normal'),
('trade.order.cancel','trade','order','cancel','V1','normal'),
('trade.contract.confirm','trade','contract','confirm','V1','medium'),
('trade.contract.review','trade','contract','review','V1','medium'),
('trade.authorization.request_extend','trade','authorization','request_extend','V1','medium'),
('billing.deposit.lock','billing','deposit','lock','V1','medium'),
('billing.deposit.read','billing','deposit','read','V1','normal'),
('billing.event.read','billing','event','read','V1','normal'),
('billing.statement.read','billing','statement','read','V1','normal'),
('billing.fee_rule.read','billing','fee_rule','read','V1','normal'),
('billing.fee_rule.manage','billing','fee_rule','manage','V1','high'),
('billing.settlement.review','billing','settlement','review','V1','medium'),
('billing.settlement.execute_manual','billing','settlement','execute_manual','V1','high'),
('billing.invoice.request','billing','invoice','request','V1','normal'),
('billing.refund.execute','billing','refund','execute','V1','high'),
('billing.compensation.execute','billing','compensation','execute','V1','high'),
('payment.provider.read','payment','provider','read','V1','normal'),
('payment.provider.manage','payment','provider','manage','V1','high'),
('payment.intent.create','payment','intent','create','V1','medium'),
('payment.intent.read','payment','intent','read','V1','normal'),
('payment.intent.cancel','payment','intent','cancel','V1','medium'),
('payment.webhook.read','payment','webhook','read','V1','medium'),
('payment.webhook.replay','payment','webhook','replay','V1','high'),
('payment.refund.manage','payment','refund','manage','V1','high'),
('payment.payout.read','payment','payout','read','V1','normal'),
('payment.payout.execute_manual','payment','payout','execute_manual','V1','high'),
('payment.reconciliation.read','payment','reconciliation','read','V1','normal'),
('payment.reconciliation.import','payment','reconciliation','import','V1','high'),
('payment.reconciliation.resolve','payment','reconciliation','resolve','V1','high'),
('delivery.file.commit','delivery','file','commit','V1','normal'),
('delivery.file.download','delivery','file','download','V1','normal'),
('delivery.trust_boundary.read','delivery','trust_boundary','read','V1','normal'),
('delivery.trust_boundary.verify','delivery','trust_boundary','verify','V1','medium'),
('delivery.api.enable','delivery','api','enable','V1','normal'),
('delivery.api.call','delivery','api','call','V1','normal'),
('delivery.api.log.read','delivery','api_log','read','V1','normal'),
('delivery.app.bind','delivery','app','bind','V1','normal'),
('delivery.sandbox.enable','delivery','sandbox','enable','V1','normal'),
('delivery.sandbox.use','delivery','sandbox','use','V1','normal'),
('delivery.report.commit','delivery','report','commit','V1','normal'),
('delivery.accept.execute','delivery','accept','execute','V1','medium'),
('delivery.reject.execute','delivery','reject','execute','V1','medium'),
('delivery.quota.read','delivery','quota','read','V1','normal'),
('delivery.ip_whitelist.manage','delivery','ip_whitelist','manage','V1','medium'),
('dispute.case.create','dispute','case','create','V1','medium'),
('dispute.case.read','dispute','case','read','V1','normal'),
('dispute.evidence.upload','dispute','evidence','upload','V1','medium'),
('dispute.evidence.read','dispute','evidence','read','V1','normal'),
('dispute.case.review','dispute','case','review','V1','medium'),
('dispute.case.resolve','dispute','case','resolve','V1','high'),
('review.subject.read','review','subject','read','V1','normal'),
('review.subject.review','review','subject','review','V1','medium'),
('review.product.read','review','product','read','V1','normal'),
('review.product.review','review','product','review','V1','medium'),
('review.compliance.read','review','compliance','read','V1','normal'),
('review.compliance.review','review','compliance','review','V1','high'),
('review.compliance.block','review','compliance','block','V1','high'),
('review.compliance.release_suggest','review','compliance','release_suggest','V1','medium'),
('risk.event.read','risk','event','read','V1','normal'),
('risk.rule.hit_handle','risk','rule','hit_handle','V1','medium'),
('risk.subject.freeze','risk','subject','freeze','V1','high'),
('risk.product.freeze','risk','product','freeze','V1','high'),
('risk.app.freeze','risk','app','freeze','V1','high'),
('audit.event.read','audit','event','read','V1','normal'),
('audit.trace.read','audit','trace','read','V1','normal'),
('audit.package.export','audit','package','export','V1','high'),
('regulator.view.read','regulator','view','read','V1','medium'),
('developer.home.read','developer','home','read','V1','normal'),
('developer.app.create','developer','app','create','V1','normal'),
('developer.app.read','developer','app','read','V1','normal'),
('developer.app.update','developer','app','update','V1','normal'),
('developer.trace.read','developer','trace','read','V1','normal'),
('developer.test_asset.read','developer','test_asset','read','V1','normal'),
('developer.mock_payment.read','developer','mock_payment','read','V1','normal'),
('developer.mock_payment.manage','developer','mock_payment','manage','V1','medium'),
('developer.mock_payment.simulate','developer','mock_payment','simulate','V1','medium'),
('security.key.read','security','key','read','V1','high'),
('security.key.revoke','security','key','revoke','V1','high'),
('security.key_envelope.manage','security','key_envelope','manage','V1','high'),
('security.cert.read','security','cert','read','V1','high'),
('security.cert.revoke','security','cert','revoke','V1','high'),
('security.token.revoke','security','token','revoke','V1','high'),
('ops.connector.manage','ops','connector','manage','V1','high'),
('ops.environment.manage','ops','environment','manage','V1','high'),
('ops.node.read','ops','node','read','V1','normal'),
('ops.node.manage','ops','node','manage','V1','high')
ON CONFLICT (permission_code) DO NOTHING;
