INSERT INTO authz.permission_definition (permission_code, domain_name, resource_name, action_name, stage_from, risk_level) VALUES
('ops.trade_monitor.read','ops','trade_monitor','read','V1','normal'),
('ops.trade_monitor.manage','ops','trade_monitor','manage','V1','high'),
('ops.external_fact.read','ops','external_fact','read','V1','normal'),
('ops.external_fact.manage','ops','external_fact','manage','V1','high'),
('ops.monitor_policy.read','ops','monitor_policy','read','V1','normal'),
('ops.monitor_policy.manage','ops','monitor_policy','manage','V1','high'),
('ops.projection_gap.read','ops','projection_gap','read','V1','normal'),
('ops.projection_gap.manage','ops','projection_gap','manage','V1','high'),
('risk.fairness_incident.read','risk','fairness_incident','read','V1','normal'),
('risk.fairness_incident.handle','risk','fairness_incident','handle','V1','high')
ON CONFLICT (permission_code) DO NOTHING;

INSERT INTO authz.role_permission (role_key, permission_code) VALUES
('platform_super_admin','ops.trade_monitor.read'),
('platform_super_admin','ops.trade_monitor.manage'),
('platform_super_admin','ops.external_fact.read'),
('platform_super_admin','ops.external_fact.manage'),
('platform_super_admin','ops.monitor_policy.read'),
('platform_super_admin','ops.monitor_policy.manage'),
('platform_super_admin','ops.projection_gap.read'),
('platform_super_admin','ops.projection_gap.manage'),
('platform_super_admin','risk.fairness_incident.read'),
('platform_super_admin','risk.fairness_incident.handle'),
('observability_operator','ops.trade_monitor.read'),
('observability_operator','ops.trade_monitor.manage'),
('observability_operator','ops.monitor_policy.read'),
('observability_operator','ops.monitor_policy.manage'),
('observability_operator','ops.external_fact.read'),
('consistency_operator','ops.trade_monitor.read'),
('consistency_operator','ops.trade_monitor.manage'),
('consistency_operator','ops.external_fact.read'),
('consistency_operator','ops.external_fact.manage'),
('consistency_operator','ops.monitor_policy.read'),
('consistency_operator','ops.projection_gap.read'),
('consistency_operator','ops.projection_gap.manage'),
('audit_admin','ops.trade_monitor.read'),
('audit_admin','ops.external_fact.read'),
('audit_admin','ops.monitor_policy.read'),
('audit_admin','ops.projection_gap.read'),
('audit_admin','risk.fairness_incident.read'),
('node_ops_admin','ops.trade_monitor.read'),
('node_ops_admin','ops.projection_gap.read'),
('risk_operator','ops.trade_monitor.read'),
('risk_operator','risk.fairness_incident.read'),
('risk_operator','risk.fairness_incident.handle'),
('finance_operator','ops.external_fact.read')
ON CONFLICT DO NOTHING;
