INSERT INTO authz.permission_definition (permission_code, domain_name, resource_name, action_name, stage_from, risk_level) VALUES
('ops.trade_monitor.read','ops','trade_monitor','read','V1','normal'),
('ops.trade_monitor.manage','ops','trade_monitor','manage','V1','high'),
('ops.external_fact.read','ops','external_fact','read','V1','normal'),
('ops.external_fact.manage','ops','external_fact','manage','V1','high'),
('ops.monitor_policy.read','ops','monitor_policy','read','V1','normal'),
('ops.monitor_policy.manage','ops','monitor_policy','manage','V1','high'),
('ops.projection_gap.read','ops','projection_gap','read','V1','normal'),
('ops.projection_gap.manage','ops','projection_gap','manage','V1','high'),
('risk.fairness_incident.read','risk','fairness_incident','read','V1','normal'),
('risk.fairness_incident.handle','risk','fairness_incident','handle','V1','high')
ON CONFLICT (permission_code) DO NOTHING;

INSERT INTO authz.role_permission (role_key, permission_code) VALUES
('platform_admin','ops.external_fact.manage'),
('platform_admin','ops.external_fact.read'),
('platform_admin','ops.monitor_policy.manage'),
('platform_admin','ops.monitor_policy.read'),
('platform_admin','ops.projection_gap.manage'),
('platform_admin','ops.projection_gap.read'),
('platform_admin','ops.trade_monitor.manage'),
('platform_admin','ops.trade_monitor.read'),
('platform_admin','risk.fairness_incident.handle'),
('platform_admin','risk.fairness_incident.read'),
('platform_audit_security','ops.external_fact.manage'),
('platform_audit_security','ops.external_fact.read'),
('platform_audit_security','ops.monitor_policy.manage'),
('platform_audit_security','ops.monitor_policy.read'),
('platform_audit_security','ops.projection_gap.manage'),
('platform_audit_security','ops.projection_gap.read'),
('platform_audit_security','ops.trade_monitor.manage'),
('platform_audit_security','ops.trade_monitor.read'),
('platform_audit_security','risk.fairness_incident.read'),
('platform_risk_settlement','ops.external_fact.read'),
('platform_risk_settlement','ops.trade_monitor.read'),
('platform_risk_settlement','risk.fairness_incident.handle'),
('platform_risk_settlement','risk.fairness_incident.read'),
('tenant_admin','ops.trade_monitor.read'),
('tenant_audit_readonly','ops.trade_monitor.read')
ON CONFLICT DO NOTHING;
