INSERT INTO authz.role_definition (role_key, role_name, role_scope, stage_from, description) VALUES
('algorithm_reviewer', '算法审核员', 'platform', 'V2', '算法审核与白名单'),
('compute_environment_operator', 'Compute Environment Operator', 'platform', 'V2', '受控计算环境管理'),
('federation_task_admin', '联邦任务管理员', 'platform', 'V2', '联邦任务协调'),
('proof_service_admin', '证明服务管理员', 'platform', 'V2', '证明材料与证明服务'),
('public_chain_admin', '公链管理员', 'platform', 'V2', '公链锚定与凭证'),
('profitshare_admin', '分润管理员', 'platform', 'V2', '分润规则与执行'),
('payout_operator', '自动打款运营员', 'platform', 'V2', '自动打款批次与失败重试'),
('channel_split_admin', '渠道分账管理员', 'platform', 'V2', '渠道分账与子商户治理'),
('execution_boundary_admin', '受控执行管理员', 'platform', 'V2', '执行边界与结果导出治理'),
('model_custody_admin', '模型托管管理员', 'tenant', 'V2', '模型权重与工件托管边界治理'),
('model_user', '模型使用者', 'tenant', 'V2', '模型商品使用'),
('federation_initiator', '联邦任务发起方', 'tenant', 'V2', '联邦任务发起'),
('federation_participant_admin', '联邦参与方管理员', 'tenant', 'V2', '联邦任务参与')
ON CONFLICT (role_key) DO NOTHING;

INSERT INTO authz.permission_definition (permission_code, domain_name, resource_name, action_name, stage_from, risk_level) VALUES
('model.asset.create','model','asset','create','V2','normal'),
('model.asset.read','model','asset','read','V2','normal'),
('model.asset.review','model','asset','review','V2','high'),
('model.asset.list','model','asset','list','V2','normal'),
('model.custody.manage','model','custody','manage','V2','high'),
('model.service.enable','model','service','enable','V2','medium'),
('model.service.read','model','service','read','V2','normal'),
('model.output.request_commercial','model','output','request_commercial','V2','high'),
('model.algorithm.upload','model','algorithm','upload','V2','medium'),
('model.algorithm.read','model','algorithm','read','V2','normal'),
('model.algorithm.review','model','algorithm','review','V2','high'),
('model.algorithm.whitelist_manage','model','algorithm','whitelist_manage','V2','high'),
('compute.task.create','compute','task','create','V2','medium'),
('compute.task.read','compute','task','read','V2','normal'),
('compute.task.review','compute','task','review','V2','high'),
('compute.task.execute','compute','task','execute','V2','high'),
('compute.result.read','compute','result','read','V2','normal'),
('compute.result.review','compute','result','review','V2','high'),
('compute.result.export','compute','result','export','V2','high'),
('compute.result_boundary.review','compute','result_boundary','review','V2','high'),
('compute.environment.manage','compute','environment','manage','V2','high'),
('compute.environment.read','compute','environment','read','V2','normal'),
('federation.task.create','federation','task','create','V2','medium'),
('federation.task.read','federation','task','read','V2','normal'),
('federation.task.start','federation','task','start','V2','high'),
('federation.task.abort','federation','task','abort','V2','high'),
('federation.participant.invite','federation','participant','invite','V2','medium'),
('federation.participant.approve','federation','participant','approve','V2','high'),
('federation.round.read','federation','round','read','V2','normal'),
('federation.round.commit','federation','round','commit','V2','medium'),
('federation.aggregate.execute','federation','aggregate','execute','V2','high'),
('federation.reward.read','federation','reward','read','V2','normal'),
('proof.artifact.read','proof','artifact','read','V2','normal'),
('proof.artifact.manage','proof','artifact','manage','V2','high'),
('proof.tee.verify','proof','tee','verify','V2','medium'),
('proof.zkp.verify','proof','zkp','verify','V2','medium'),
('proof.reference.bind','proof','reference','bind','V2','medium'),
('proof.reference.revoke','proof','reference','revoke','V2','high'),
('profitshare.rule.read','profitshare','rule','read','V2','normal'),
('profitshare.rule.manage','profitshare','rule','manage','V2','high'),
('profitshare.contribution.read','profitshare','contribution','read','V2','normal'),
('profitshare.contribution.review','profitshare','contribution','review','V2','high'),
('profitshare.reward.read','profitshare','reward','read','V2','normal'),
('profitshare.reward.review','profitshare','reward','review','V2','high'),
('profitshare.reward.execute','profitshare','reward','execute','V2','high'),
('profitshare.reward.freeze','profitshare','reward','freeze','V2','high'),
('payment.payout.execute_auto','payment','payout','execute_auto','V2','high'),
('payment.split.manage','payment','split','manage','V2','high'),
('payment.split.execute','payment','split','execute','V2','high'),
('payment.sub_merchant.manage','payment','sub_merchant','manage','V2','high'),
('publicchain.anchor.submit','publicchain','anchor','submit','V2','medium'),
('publicchain.anchor.read','publicchain','anchor','read','V2','normal'),
('publicchain.credential.issue','publicchain','credential','issue','V2','high'),
('publicchain.credential.revoke','publicchain','credential','revoke','V2','high'),
('publicchain.credential.hide','publicchain','credential','hide','V2','medium'),
('publicchain.verify_page.read','publicchain','verify_page','read','V2','normal')
ON CONFLICT (permission_code) DO NOTHING;
